server:
  port: 8000

spring:
  application:
    name: pet-project
  security:
    user:
      name: admin
      password: password
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
        temp:
          use_jdbc_metadata_defaults: false
        default_schema: pet_project
        jdbc:
          batch_size: 1000
        order_inserts: true
    open-in-view: false
  datasource:
    url: jdbc:p6spy:postgresql://localhost:5432/pet
    username: safs
    password: safs
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: HikariPool
      max-lifetime: 600000
      connection-timeout: 15000
      maximum-pool-size: 10
      idle-timeout: 200000
      minimum-idle: 2
      schema: pet_project
  liquibase:
    enabled: true
    url: jdbc:postgresql://localhost:5432/pet
    default-schema: pet_project
    user: safs
    password: safs
    change-log: file:src/main/resources/liquibase/changelog.yaml
    contexts: develop

logging:
  config: src/main/resources/logback.groovy

logbook:
  strategy: body-only-if-status-at-least
  exclude:
    - /actuator/health
  format:
    style: http
  logger:
    name: PET-PROJECT-REST
    level: info